CREATE USER dlta IDENTIFIED BY dlta;

GRANT CONNECT TO dlta;
GRANT CREATE SESSION TO dlta;
GRANT GRANT ANY PRIVILEGE TO dlta;
GRANT UNLIMITED TABLESPACE TO dlta;
GRANT CREATE SEQUENCE TO dlta;
GRANT CREATE TABLE TO dlta;
--GRANT CREATE VIEW TO dlta;
GRANT CREATE PROCEDURE TO dlta;
--GRANT CREATE TYPE TO dlta;